import Magma.CatKripkeWallMinimal

/-!
# N=10 Independence Countermodels

Three concrete 10-element counterexamples completing the full independence matrix:

1. **D ⊬ H (no Compose)**: A DichotomicRetractMagma where no element satisfies Compose.
2. **H ⊬ D (diagonal)**: A FaithfulRetractMagma with Branch+Compose+Y that violates Kripke.

Tables generated by Z3 SAT solver, verified independently, frozen in counterexamples.json.
All proofs by `native_decide`.
-/

set_option autoImplicit false

namespace KripkeWall

-- ═══════════════════════════════════════════════════════════════════
-- 1. D ⊬ H: DichotomicRetractMagma with no Compose element
-- ═══════════════════════════════════════════════════════════════════

private def rawDnotH : Nat → Nat → Nat
  | 0, _ => 0
  | 1, _ => 1
  | 2, 0 => 3 | 2, 1 => 3 | 2, 2 => 2 | 2, 3 => 3 | 2, 4 => 4 | 2, 5 => 5 | 2, 6 => 6 | 2, 7 => 7 | 2, 8 => 9 | 2, 9 => 8
  | 3, 0 => 0 | 3, 1 => 1 | 3, 2 => 2 | 3, 3 => 3 | 3, 4 => 4 | 3, 5 => 5 | 3, 6 => 6 | 3, 7 => 7 | 3, 8 => 9 | 3, 9 => 8
  | 4, 0 => 0 | 4, 1 => 0 | 4, 2 => 1 | 4, 3 => 1 | 4, 4 => 1 | 4, 5 => 1 | 4, 6 => 1 | 4, 7 => 1 | 4, 8 => 1 | 4, 9 => 1
  | 5, 0 => 1 | 5, 1 => 0 | 5, 2 => 0 | 5, 3 => 0 | 5, 4 => 0 | 5, 5 => 0 | 5, 6 => 0 | 5, 7 => 0 | 5, 8 => 0 | 5, 9 => 0
  | 6, 0 => 2 | 6, 1 => 3 | 6, 2 => 9 | 6, 3 => 9 | 6, 4 => 9 | 6, 5 => 9 | 6, 6 => 9 | 6, 7 => 9 | 6, 8 => 9 | 6, 9 => 8
  | 7, 0 => 3 | 7, 1 => 2 | 7, 2 => 9 | 7, 3 => 9 | 7, 4 => 9 | 7, 5 => 9 | 7, 6 => 9 | 7, 7 => 9 | 7, 8 => 9 | 7, 9 => 8
  | 8, 0 => 1 | 8, 1 => 0 | 8, 2 => 1 | 8, 3 => 0 | 8, 4 => 1 | 8, 5 => 1 | 8, 6 => 1 | 8, 7 => 1 | 8, 8 => 0 | 8, 9 => 0
  | 9, 0 => 0 | 9, 1 => 1 | 9, 2 => 0 | 9, 3 => 1 | 9, 4 => 0 | 9, 5 => 1 | 9, 6 => 1 | 9, 7 => 0 | 9, 8 => 1 | 9, 9 => 1
  | _, _ => 0

private theorem rawDnotH_bound (a b : Fin 10) : rawDnotH a.val b.val < 10 := by
  revert a b; native_decide

def dotDnotH (a b : Fin 10) : Fin 10 := ⟨rawDnotH a.val b.val, rawDnotH_bound a b⟩

/-- D ⊬ H counterexample: a 10-element DichotomicRetractMagma.
    Has Kripke dichotomy but no element satisfies Compose. -/
def dNotH : DichotomicRetractMagma 10 where
  dot := dotDnotH
  zero₁ := 0
  zero₂ := 1
  sec := 2
  ret := 3
  cls := 4
  zero₁_left := by native_decide
  zero₂_left := by native_decide
  zeros_distinct := by native_decide
  no_other_zeros := by native_decide
  extensional := by native_decide
  ret_sec := by native_decide
  sec_ret := by native_decide
  ret_zero₁ := by native_decide
  cls_boolean := by native_decide
  cls_ne_zero₁ := by native_decide
  cls_ne_zero₂ := by native_decide
  dichotomy := by native_decide
  has_non_classifier := by native_decide

/-- No element of the D⊬H model satisfies the Compose axiom η·x = ρ·(g·x)
    where ρ=7, g=6. For every candidate η, some core element x witnesses failure. -/
theorem dNotH_no_compose :
    ∀ η : Fin 10,
      ∃ x : Fin 10, x ≠ (0 : Fin 10) ∧ x ≠ (1 : Fin 10) ∧
        dotDnotH η x ≠ dotDnotH 7 (dotDnotH 6 x) := by
  native_decide

-- ═══════════════════════════════════════════════════════════════════
-- 2. H ⊬ D: FaithfulRetractMagma with Branch+Compose+Y, no Kripke
-- ═══════════════════════════════════════════════════════════════════

private def rawHnotD : Nat → Nat → Nat
  | 0, _ => 0
  | 1, _ => 1
  | 2, 0 => 3 | 2, 1 => 1 | 2, 2 => 3 | 2, 3 => 4 | 2, 4 => 9 | 2, 5 => 6 | 2, 6 => 8 | 2, 7 => 5 | 2, 8 => 7 | 2, 9 => 2
  | 3, 0 => 0 | 3, 1 => 1 | 3, 2 => 9 | 3, 3 => 2 | 3, 4 => 3 | 3, 5 => 7 | 3, 6 => 5 | 3, 7 => 8 | 3, 8 => 6 | 3, 9 => 4
  | 4, 0 => 0 | 4, 1 => 0 | 4, 2 => 1 | 4, 3 => 1 | 4, 4 => 1 | 4, 5 => 1 | 4, 6 => 1 | 4, 7 => 1 | 4, 8 => 0 | 4, 9 => 0
  | 5, 0 => 0 | 5, 1 => 0 | 5, 2 => 2 | 5, 3 => 0 | 5, 4 => 0 | 5, 5 => 0 | 5, 6 => 0 | 5, 7 => 0 | 5, 8 => 3 | 5, 9 => 1
  | 6, 0 => 2 | 6, 1 => 2 | 6, 2 => 2 | 6, 3 => 8 | 6, 4 => 3 | 6, 5 => 9 | 6, 6 => 4 | 6, 7 => 7 | 6, 8 => 9 | 6, 9 => 7
  | 7, 0 => 8 | 7, 1 => 3 | 7, 2 => 2 | 7, 3 => 8 | 7, 4 => 3 | 7, 5 => 9 | 7, 6 => 4 | 7, 7 => 7 | 7, 8 => 3 | 7, 9 => 1
  | 8, 0 => 9 | 8, 1 => 2 | 8, 2 => 2 | 8, 3 => 3 | 8, 4 => 8 | 8, 5 => 1 | 8, 6 => 3 | 8, 7 => 7 | 8, 8 => 1 | 8, 9 => 7
  | 9, 0 => 2 | 9, 1 => 2 | 9, 2 => 2 | 9, 3 => 2 | 9, 4 => 4 | 9, 5 => 7 | 9, 6 => 6 | 9, 7 => 7 | 9, 8 => 2 | 9, 9 => 0
  | _, _ => 0

private theorem rawHnotD_bound (a b : Fin 10) : rawHnotD a.val b.val < 10 := by
  revert a b; native_decide

def dotHnotD (a b : Fin 10) : Fin 10 := ⟨rawHnotD a.val b.val, rawHnotD_bound a b⟩

/-- H ⊬ D counterexample: a 10-element FaithfulRetractMagma.
    Has all evaluation machinery but violates Kripke dichotomy. -/
def hNotD : FaithfulRetractMagma 10 where
  dot := dotHnotD
  zero₁ := 0
  zero₂ := 1
  sec := 2
  ret := 3
  zero₁_left := by native_decide
  zero₂_left := by native_decide
  zeros_distinct := by native_decide
  no_other_zeros := by native_decide
  extensional := by native_decide
  ret_sec := by native_decide
  sec_ret := by native_decide
  ret_zero₁ := by native_decide

/-- E-transparency. -/
theorem hNotD_e_transparent :
    dotHnotD 3 0 = 0 ∧ dotHnotD 3 1 = 1 := by native_decide

/-- Classifier at index 4: all outputs boolean. -/
theorem hNotD_has_classifier :
    ∀ x : Fin 10, dotHnotD 4 x = 0 ∨ dotHnotD 4 x = 1 := by native_decide

/-- Branch: ρ(7)·x = f(5)·x when τ(4)·x = 0, else ρ·x = g(6)·x, on core. -/
theorem hNotD_branch :
    ∀ x : Fin 10, x ≠ (0 : Fin 10) → x ≠ (1 : Fin 10) →
      (dotHnotD 4 x = 0 → dotHnotD 7 x = dotHnotD 5 x) ∧
      (dotHnotD 4 x ≠ 0 → dotHnotD 7 x = dotHnotD 6 x) := by
  native_decide

/-- Compose: η(8)·x = ρ(7)·(g(6)·x) on core. -/
theorem hNotD_compose :
    ∀ x : Fin 10, x ≠ (0 : Fin 10) → x ≠ (1 : Fin 10) →
      dotHnotD 8 x = dotHnotD 7 (dotHnotD 6 x) := by
  native_decide

/-- Inert: g(6) maps core away from absorbers. -/
theorem hNotD_inert :
    ∀ x : Fin 10, x ≠ (0 : Fin 10) → x ≠ (1 : Fin 10) →
      dotHnotD 6 x ≠ 0 ∧ dotHnotD 6 x ≠ 1 := by
  native_decide

/-- Y fixed-point: Y(9)·ρ(7) = ρ·(Y·ρ) and Y·ρ ≥ 2. -/
theorem hNotD_y_fixpoint :
    dotHnotD 9 7 = dotHnotD 7 (dotHnotD 9 7) ∧ (dotHnotD 9 7).val ≥ 2 := by
  native_decide

/-- **The diagonal independence theorem**: the Kripke dichotomy fails
    despite all evaluation machinery being present.
    Element 5 has both boolean and non-boolean outputs on core. -/
theorem hNotD_violates_dichotomy :
    ¬ (∀ y : Fin 10, y ≠ hNotD.zero₁ → y ≠ hNotD.zero₂ →
      (∀ x : Fin 10, x ≠ hNotD.zero₁ → x ≠ hNotD.zero₂ →
        hNotD.dot y x = hNotD.zero₁ ∨ hNotD.dot y x = hNotD.zero₂) ∨
      (∀ x : Fin 10, x ≠ hNotD.zero₁ → x ≠ hNotD.zero₂ →
        hNotD.dot y x ≠ hNotD.zero₁ ∧ hNotD.dot y x ≠ hNotD.zero₂)) := by
  native_decide

/-- Combined: the H⊬D model has ALL evaluation machinery AND violates Kripke. -/
theorem h_independent_of_dichotomy :
    ∃ (_ : FaithfulRetractMagma 10),
    -- Branch holds
    (∀ x : Fin 10, x ≠ (0 : Fin 10) → x ≠ (1 : Fin 10) →
      (dotHnotD 4 x = 0 → dotHnotD 7 x = dotHnotD 5 x) ∧
      (dotHnotD 4 x ≠ 0 → dotHnotD 7 x = dotHnotD 6 x)) ∧
    -- Compose holds
    (∀ x : Fin 10, x ≠ (0 : Fin 10) → x ≠ (1 : Fin 10) →
      dotHnotD 8 x = dotHnotD 7 (dotHnotD 6 x)) ∧
    -- Y holds
    (dotHnotD 9 7 = dotHnotD 7 (dotHnotD 9 7) ∧ (dotHnotD 9 7).val ≥ 2) ∧
    -- Kripke fails
    ¬ (∀ y : Fin 10, y ≠ hNotD.zero₁ → y ≠ hNotD.zero₂ →
      (∀ x : Fin 10, x ≠ hNotD.zero₁ → x ≠ hNotD.zero₂ →
        hNotD.dot y x = hNotD.zero₁ ∨ hNotD.dot y x = hNotD.zero₂) ∨
      (∀ x : Fin 10, x ≠ hNotD.zero₁ → x ≠ hNotD.zero₂ →
        hNotD.dot y x ≠ hNotD.zero₁ ∧ hNotD.dot y x ≠ hNotD.zero₂)) :=
  ⟨hNotD, hNotD_branch, hNotD_compose, hNotD_y_fixpoint, hNotD_violates_dichotomy⟩

end KripkeWall
