import Magma.CatKripkeWallMinimal

/-!
# The Countermodel: FRM ⊬ Kripke Dichotomy

A concrete 8-element FaithfulRetractMagma that satisfies all retraction axioms
(extensionality, two absorbers, retraction pair) but violates the Kripke dichotomy.

Element 5 has *mixed* outputs on the core: both boolean ({0,1}-valued) and
non-boolean (≥2). This proves that self-simulation infrastructure (retraction pair)
does not force self-description (clean separation of classifiers and non-classifiers).

**Independence result**: FaithfulRetractMagma ⊬ DichotomicRetractMagma.
The Kripke dichotomy is independent of self-simulation.

Table generated by Z3 SAT solver, verified independently, frozen in counterexamples.json.
-/

set_option autoImplicit false

namespace KripkeWall

/-- The raw 8×8 Cayley table of The Countermodel. -/
private def rawPC8 : Nat → Nat → Nat
  -- Row 0: ⊤ (absorber)
  | 0, _ => 0
  -- Row 1: ⊥ (absorber)
  | 1, _ => 1
  -- Row 2: Q (section) — permutation on core, QE round-trip
  | 2, 0 => 3 | 2, 1 => 3 | 2, 2 => 7 | 2, 3 => 3 | 2, 4 => 4 | 2, 5 => 6 | 2, 6 => 5 | 2, 7 => 2
  -- Row 3: E (retraction) — E-transparent, QE round-trip
  | 3, 0 => 0 | 3, 1 => 1 | 3, 2 => 7 | 3, 3 => 3 | 3, 4 => 4 | 3, 5 => 6 | 3, 6 => 5 | 3, 7 => 2
  -- Row 4: classifier — all outputs in {0,1}
  | 4, 0 => 0 | 4, 1 => 0 | 4, 2 => 0 | 4, 3 => 0 | 4, 4 => 0 | 4, 5 => 0 | 4, 6 => 1 | 4, 7 => 0
  -- Row 5: MIXED — has both boolean (1) and non-boolean (6,2) outputs on core
  | 5, 0 => 6 | 5, 1 => 2 | 5, 2 => 6 | 5, 3 => 2 | 5, 4 => 1 | 5, 5 => 1 | 5, 6 => 1 | 5, 7 => 1
  -- Row 6: encoder — all core outputs ≥ 2
  | 6, 0 => 0 | 6, 1 => 0 | 6, 2 => 5 | 6, 3 => 2 | 6, 4 => 2 | 6, 5 => 2 | 6, 6 => 2 | 6, 7 => 2
  -- Row 7: MIXED — has boolean (1) and non-boolean (2,6,3) outputs on core
  | 7, 0 => 2 | 7, 1 => 2 | 7, 2 => 2 | 7, 3 => 1 | 7, 4 => 2 | 7, 5 => 2 | 7, 6 => 6 | 7, 7 => 3
  | _, _ => 0

private theorem rawPC8_bound (a b : Fin 8) : rawPC8 a.val b.val < 8 := by
  revert a b; decide

/-- The binary operation of The Countermodel. -/
def dotPC8 (a b : Fin 8) : Fin 8 := ⟨rawPC8 a.val b.val, rawPC8_bound a b⟩

/-- **The Countermodel**: an 8-element FaithfulRetractMagma.
    Has two absorbers (0,1), a retraction pair (Q=2, E=3),
    extensionality, and E-transparency. -/
def countermodel8 : FaithfulRetractMagma 8 where
  dot := dotPC8
  zero₁ := 0
  zero₂ := 1
  sec := 2
  ret := 3
  zero₁_left := by decide
  zero₂_left := by decide
  zeros_distinct := by decide
  no_other_zeros := by decide
  extensional := by decide
  ret_sec := by decide
  sec_ret := by decide
  ret_zero₁ := by decide

-- ═══════════════════════════════════════════════════════════════════
-- Key theorems
-- ═══════════════════════════════════════════════════════════════════

/-- E-transparency: E(⊤) = ⊤ and E(⊥) = ⊥. -/
theorem countermodel8_e_transparent :
    countermodel8.dot 3 0 = 0 ∧ countermodel8.dot 3 1 = 1 := by
  decide

/-- Element 4 is a classifier: all outputs are in {zero₁, zero₂}. -/
theorem countermodel8_has_classifier :
    ∀ x : Fin 8,
      countermodel8.dot 4 x = countermodel8.zero₁ ∨
      countermodel8.dot 4 x = countermodel8.zero₂ := by
  decide

/-- Element 5 is mixed: it produces both boolean and non-boolean outputs on core.
    Specifically, dot(5,4) = 1 ∈ {0,1} but dot(5,2) = 6 ∉ {0,1}. -/
theorem countermodel8_element5_mixed :
    let M := countermodel8
    -- Element 5 is not an absorber
    (5 : Fin 8) ≠ M.zero₁ ∧ (5 : Fin 8) ≠ M.zero₂ ∧
    -- It has a boolean output on core (dot(5,4) = 1 = zero₂)
    (∃ x : Fin 8, x ≠ M.zero₁ ∧ x ≠ M.zero₂ ∧
      (M.dot 5 x = M.zero₁ ∨ M.dot 5 x = M.zero₂)) ∧
    -- It also has a non-boolean output on core (dot(5,2) = 6)
    (∃ x : Fin 8, x ≠ M.zero₁ ∧ x ≠ M.zero₂ ∧
      M.dot 5 x ≠ M.zero₁ ∧ M.dot 5 x ≠ M.zero₂) := by
  decide

/-- **The independence theorem**: the Kripke dichotomy does not hold
    for The Countermodel. There exists a non-absorber whose
    core outputs are neither all-boolean nor all-non-boolean. -/
theorem countermodel8_violates_dichotomy :
    ¬ (∀ y : Fin 8, y ≠ countermodel8.zero₁ → y ≠ countermodel8.zero₂ →
      (∀ x : Fin 8, x ≠ countermodel8.zero₁ → x ≠ countermodel8.zero₂ →
        countermodel8.dot y x = countermodel8.zero₁ ∨
        countermodel8.dot y x = countermodel8.zero₂) ∨
      (∀ x : Fin 8, x ≠ countermodel8.zero₁ → x ≠ countermodel8.zero₂ →
        countermodel8.dot y x ≠ countermodel8.zero₁ ∧
        countermodel8.dot y x ≠ countermodel8.zero₂)) := by
  decide

/-- Combined: The Countermodel is a FaithfulRetractMagma (self-simulation
    infrastructure) with a classifier, but NOT a DichotomicRetractMagma
    (self-description structure). This is the S ⊬ D independence result. -/
theorem frm_independent_of_dichotomy :
    ∃ (_ : FaithfulRetractMagma 8),
    -- Has a classifier (element 4)
    (∀ x : Fin 8, countermodel8.dot 4 x = countermodel8.zero₁ ∨
                   countermodel8.dot 4 x = countermodel8.zero₂) ∧
    -- But violates the dichotomy
    ¬ (∀ y : Fin 8, y ≠ countermodel8.zero₁ → y ≠ countermodel8.zero₂ →
      (∀ x : Fin 8, x ≠ countermodel8.zero₁ → x ≠ countermodel8.zero₂ →
        countermodel8.dot y x = countermodel8.zero₁ ∨
        countermodel8.dot y x = countermodel8.zero₂) ∨
      (∀ x : Fin 8, x ≠ countermodel8.zero₁ → x ≠ countermodel8.zero₂ →
        countermodel8.dot y x ≠ countermodel8.zero₁ ∧
        countermodel8.dot y x ≠ countermodel8.zero₂)) :=
  ⟨countermodel8, countermodel8_has_classifier, countermodel8_violates_dichotomy⟩

end KripkeWall
