import Magma.CatKripkeWallMinimal
import Magma.ICP

/-!
# Lean-Verified Coexistence Witness: R+D+ICP at N=6

A concrete 6-element algebra satisfying all three capabilities simultaneously:
  R (self-representation): retraction pair Q(2)/E(3) with E-transparency
  D (self-description): classifier τ(4) with Kripke dichotomy
  H (self-execution): ICP witnessed by a=2, b=3, c=5

**Minimum cardinality**: This is the smallest known witness for R+D+H coexistence.
The retraction pair members (2, 3) serve simultaneously as ICP witnesses,
demonstrating that role overlap enables coexistence below N=10.

Table generated by Z3 SAT solver, independently verified in Lean.
-/

set_option autoImplicit false

namespace KripkeWall

-- ═══════════════════════════════════════════════════════════════════
-- The N=6 R+D+ICP witness
-- ═══════════════════════════════════════════════════════════════════

private def rawW6 : Nat → Nat → Nat
  | 0, 0 => 0 | 0, 1 => 0 | 0, 2 => 0 | 0, 3 => 0 | 0, 4 => 0 | 0, 5 => 0
  | 1, 0 => 1 | 1, 1 => 1 | 1, 2 => 1 | 1, 3 => 1 | 1, 4 => 1 | 1, 5 => 1
  | 2, 0 => 3 | 2, 1 => 3 | 2, 2 => 4 | 2, 3 => 2 | 2, 4 => 5 | 2, 5 => 3
  | 3, 0 => 0 | 3, 1 => 1 | 3, 2 => 3 | 3, 3 => 5 | 3, 4 => 2 | 3, 5 => 4
  | 4, 0 => 0 | 4, 1 => 0 | 4, 2 => 1 | 4, 3 => 0 | 4, 4 => 1 | 4, 5 => 1
  | 5, 0 => 2 | 5, 1 => 2 | 5, 2 => 5 | 5, 3 => 4 | 5, 4 => 3 | 5, 5 => 2
  | _, _ => 0

private theorem rawW6_bound (a b : Fin 6) : rawW6 a.val b.val < 6 := by
  revert a b; decide

def dotW6 (a b : Fin 6) : Fin 6 := ⟨rawW6 a.val b.val, rawW6_bound a b⟩

-- ═══════════════════════════════════════════════════════════════════
-- Capability R: FaithfulRetractMagma (self-representation)
-- ═══════════════════════════════════════════════════════════════════

/-- The N=6 witness is a FaithfulRetractMagma with Q=2, E=3. -/
def witness6_frm : FaithfulRetractMagma 6 where
  dot := dotW6
  zero₁ := 0
  zero₂ := 1
  sec := 2
  ret := 3
  zero₁_left := by decide
  zero₂_left := by decide
  zeros_distinct := by decide
  no_other_zeros := by decide
  extensional := by decide
  ret_sec := by decide
  sec_ret := by decide
  ret_zero₁ := by decide

/-- E-transparency: E(⊤) = ⊤, E(⊥) = ⊥. -/
theorem witness6_e_transparent :
    dotW6 3 0 = 0 ∧ dotW6 3 1 = 1 := by decide

-- ═══════════════════════════════════════════════════════════════════
-- Capability D: DichotomicRetractMagma (self-description)
-- ═══════════════════════════════════════════════════════════════════

/-- The N=6 witness is a DichotomicRetractMagma with τ=4. -/
def witness6_drm : DichotomicRetractMagma 6 where
  dot := dotW6
  zero₁ := 0
  zero₂ := 1
  sec := 2
  ret := 3
  cls := 4
  zero₁_left := by decide
  zero₂_left := by decide
  zeros_distinct := by decide
  no_other_zeros := by decide
  extensional := by decide
  ret_sec := by decide
  sec_ret := by decide
  ret_zero₁ := by decide
  cls_boolean := by decide
  cls_ne_zero₁ := by decide
  cls_ne_zero₂ := by decide
  dichotomy := by decide
  has_non_classifier := by decide

-- ═══════════════════════════════════════════════════════════════════
-- Capability H: ICP (self-execution)
-- ═══════════════════════════════════════════════════════════════════

/-- ICP holds at N=6, witnessed by a=2, b=3, c=5.
    Note: a=2 (Q) and b=3 (E) are the retraction pair — role overlap. -/
theorem w6_has_icp : HasICP 6 dotW6 0 1 := by decide

-- ═══════════════════════════════════════════════════════════════════
-- Coexistence witness theorem
-- ═══════════════════════════════════════════════════════════════════

/-- **Lean-verified coexistence**: R+D+ICP all hold at N=6.
    This is the smallest known witness for simultaneous R+D+H. -/
theorem sdh_witness_6 :
    ∃ (_ : FaithfulRetractMagma 6),
    ∃ (_ : DichotomicRetractMagma 6),
    HasICP 6 dotW6 0 1 :=
  ⟨witness6_frm, witness6_drm, w6_has_icp⟩

end KripkeWall
